<a href="https://colab.research.google.com/github/faryal-art/week4_pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## chapter-00: PyTorch fundamentals
Resource notebook:  https://www.learnpytorch.io/00_pytorch_fundamentals/

### 1.   What is machine learning?
Machine Learning is a way to teach computers to learn from data and make decisions without being directly programmed.

### 2.  What is deep learning ?
Deep Learning is a type of machine learning where computers learn from large amounts of data using multi-layered neural networks, just like how our brain works.

### 3.  What is neural network?
Neural Network is a model in deep learning made up of layers of connected nodes (like brain neurons) that helps a computer learn patterns from data to make predictions or decisions.

### 4.  What is pytorch ?
PyTorch is an open-source deep learning library that makes it easy to build, train, and test neural networks using Python — it's popular for its flexibility and simplicity.

### 5. why we use it ?
We use PyTorch because it makes building and training deep learning models:

✅ Simple and intuitive with easy-to-read Python code

✅ Flexible for experimentation and research

✅ Powerful with GPU support using CUDA

✅ Popular in the AI community with strong documentation and tools

✅ Efficient for both beginners and professionals in machine learning and deep learning tasks

In short: PyTorch helps us quickly build smart models that learn from data.
### 6.  what are tensor ?
A tensor is a container for numbers arranged in 0 or more dimensions — like a number, a list, a matrix, or even higher-dimensional data — and it's the basic data type used in PyTorch for building and training model



In [429]:
### importing libraries
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### creating tensors
1. tensors are main building block of data / deep learning in general .
2.  Tensors are way to represent data specially multi-dimensional data
3. torch.tensor() is  a function to create tensor

In [430]:
#scalar
scalar=torch.tensor(712)
scalar


tensor(712)

In [431]:
# to check number of  dimensions the tensor has
scalar.ndim

0

In [432]:
#to convert number back to python int/float
scalar.item()

712

In [433]:
vector=torch.tensor([7,12])
vector

tensor([ 7, 12])

In [434]:
vector.ndim

1

In [435]:
vector.shape

torch.Size([2])

In [436]:
#indexing getting values using indexes
vector[:]

tensor([ 7, 12])

In [437]:
vector[1]

tensor(12)

In [438]:
vector[0]

tensor(7)

In [439]:
#MATRIX
MATRIX= torch.tensor([[1,2],[7,3]])
MATRIX

tensor([[1, 2],
        [7, 3]])

In [440]:
MATRIX.ndim

2

In [441]:
MATRIX.shape

torch.Size([2, 2])

In [442]:
MATRIX[0]

tensor([1, 2])

In [443]:
#INDEXING ON MATRIX
MATRIX[1][1]

tensor(3)

In [444]:
#tensors
TENSOR=torch.tensor([[[1,2,3],[5,7,9],[2,4,6]]])
t1

NameError: name 't1' is not defined

In [ ]:
TENSOR.ndim

In [ ]:
TENSOR.shape

In [ ]:
TENSOR[0]

In [ ]:
TENSOR=torch.tensor([[[[[1,7],[6,9]]]]])
TENSOR

In [445]:
TENSOR.ndim

3

In [446]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random  tensor
 Why random tensors ?
 Random Tensors are important as many neural networks learn the way they
 * starts with tensors full of random numbers
 * And then adjust those random numbers in tensors to represent data in better way

 #### core idea of neural network
 ` Start with random numbers -> look at data  -> update random numbers -> look at data -> update random numbers `



In [447]:
#create a random tensor of size(2,3)
random_tensor= torch.rand(3)
random_tensor

tensor([0.8694, 0.5677, 0.7411])

In [448]:
random_tensor.shape

torch.Size([3])

In [449]:
random_tensor.ndim

1

In [450]:
rt2=torch.rand(2,3)
rt2


tensor([[0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696]])

In [451]:
rt2.ndim

2

In [452]:
random4=torch.rand(1,5,5)
random4

tensor([[[0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062, 0.9516],
         [0.0753, 0.8860, 0.5832, 0.3376, 0.8090],
         [0.5779, 0.9040, 0.5547, 0.3423, 0.6343],
         [0.3644, 0.7104, 0.9464, 0.7890, 0.2814]]])

In [453]:
random4.ndim

3

In [454]:
random4.shape

torch.Size([1, 5, 5])

In [455]:
# the first digit in the bracket tells how many batches we created like in this we have created  2 batches of 5x5 matrix
random3=torch.rand(2,5,5)
random3

tensor([[[0.7886, 0.5895, 0.7539, 0.1952, 0.0050],
         [0.3068, 0.1165, 0.9103, 0.6440, 0.7071],
         [0.6581, 0.4913, 0.8913, 0.1447, 0.5315],
         [0.1587, 0.6542, 0.3278, 0.6532, 0.3958],
         [0.9147, 0.2036, 0.2018, 0.2018, 0.9497]],

        [[0.6666, 0.9811, 0.0874, 0.0041, 0.1088],
         [0.1637, 0.7025, 0.6790, 0.9155, 0.2418],
         [0.1591, 0.7653, 0.2979, 0.8035, 0.3813],
         [0.7860, 0.1115, 0.2477, 0.6524, 0.6057],
         [0.3725, 0.7980, 0.8399, 0.1374, 0.2331]]])

In [456]:
random3.ndim

3

In [457]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(3,244,244) #color channel(R,B,G), Height,Width
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

In [458]:
#it does not matter much if we write size or not
random5=torch.rand(size =(4,3))
random5

tensor([[0.1353, 0.1691, 0.8853],
        [0.4241, 0.4636, 0.7870],
        [0.9211, 0.5783, 0.9248],
        [0.2644, 0.8052, 0.4260]])

### Zeros and ones
Creating tensors with Zeros and ones

In [459]:
# create a tensor of all Zeros
zero_tensor=torch.zeros( size=(4,3))
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [460]:
zero_tensor*random5

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [461]:
ones_tensor=torch.ones(size= (4,5))
ones_tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [462]:
ones_tensor.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [463]:
# Use torch.arange ()
num_range=torch.arange(1,15)
num_range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [464]:
"size /shape= ", num_range.shape,"Dimensions =" ,num_range.ndim

('size /shape= ', torch.Size([14]), 'Dimensions =', 1)

In [465]:
number1_t0_10=torch.arange(start=1,end=11,step=1)
number1_t0_10

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [466]:
number1_t0_10.ndim

1

In [467]:
multiples_of_3=torch.arange(start=3,end=33,step=3)
multiples_of_3


tensor([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [468]:
#Creating tensor like
ten_zeros=torch.zeros_like(input=number1_t0_10)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor data types
* Tensor datatypes is one of thr 3 big issues/errors you will run into with Pytorch and deep learning:
1. Tensor not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [469]:
#float 32 tensor (a tensor data type)
float_32_tensor=torch.tensor([1.0,3.0,5.0],
                             dtype= None, #what data type a tensor is
                             device= None, # by default `cpu`. what device is your tensor on
                             requires_grad=False, #whether or not to track gradients with this tensor operations
                             )
float_32_tensor

tensor([1., 3., 5.])

In [470]:
float_32_tensor.dtype # torch.float=float32

torch.float32

In [471]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 3., 5.], dtype=torch.float16)

In [472]:
#other way to make tensor 32 to tensor 16
float_16_tensor=float_32_tensor.type(torch.half)
float_16_tensor

tensor([1., 3., 5.], dtype=torch.float16)

In [473]:
result=float_32_tensor*float_16_tensor
result

tensor([ 1.,  9., 25.])

In [474]:
result.dtype

torch.float32

In [475]:
int_32_tensor=torch.tensor([2,4,6], dtype=torch.int32)
int_32_tensor

tensor([2, 4, 6], dtype=torch.int32)

In [476]:
r=float_32_tensor*int_32_tensor
r,r.dtype

(tensor([ 2., 12., 30.]), torch.float32)

In [477]:
#float64 is same as torch.double
float_64_tensor=torch.tensor([1,6,9],dtype=torch.double)
float_64_tensor


tensor([1., 6., 9.], dtype=torch.float64)

In [478]:
# try with long tensor
#torch.long is another name/word of int64  tensor
long_tensor=torch.tensor([1,3,7],dtype=torch.long)
long_tensor, long_tensor.dtype

(tensor([1, 3, 7]), torch.int64)

In [479]:
 #multiply int32 with int64
 r2=int_32_tensor*long_tensor
 r2,r2.dtype

(tensor([ 2, 12, 42]), torch.int64)

#Getting information from tensor(tensor attributes)
1.   Tensor not right shape _ to get shape we can use `tensor.shape`
2.  Tensor not right datatype_ to get datatype we use `tensor.dtype`
3. Tensor not on right device_to get device(CPU,GPU) from tensor `tensor.device`


In [480]:
# create a tensor
random_tensor=torch.rand(4,3)
random_tensor

tensor([[0.2986, 0.2240, 0.0445],
        [0.2675, 0.6754, 0.7022],
        [0.3396, 0.1839, 0.9218],
        [0.9206, 0.3369, 0.3539]])

In [481]:
#find out details about tensor
print(f"tensor:  {random_tensor}")
print(f"Shape of tensor: {random_tensor.shape}")
print(f"Datatype of tensor: {random_tensor.dtype}" )
print(f"Device tensor is on: {random_tensor.device}")

tensor:  tensor([[0.2986, 0.2240, 0.0445],
        [0.2675, 0.6754, 0.7022],
        [0.3396, 0.1839, 0.9218],
        [0.9206, 0.3369, 0.3539]])
Shape of tensor: torch.Size([4, 3])
Datatype of tensor: torch.float32
Device tensor is on: cpu


In [482]:
random1_tensor=torch.rand((5,4),device=GPU)
#random1_tensor=random1_tensor.device=None
random1_tensor.device

NameError: name 'GPU' is not defined

### Tenosrs manipulation(tensors operations)
Tensor operations include
1. Addition
2. Subraction
3. Multiplication(element wise)
4. Division
5. Matrix multiplication


In [ ]:
# Addition
#create a tensor and add something in it
tensor1=torch.tensor([1,5,8])
tensor1+20 # + operator is used for addition

In [ ]:
#Multiplication
tensor1*10  # * operator is used for multiplication

In [ ]:
tensor1

In [ ]:
#trying pytorch in-built functions
tensor2=torch.tensor([3,6,9])
torch.mul(tensor1,10) #mul short form for multiplication

In [483]:
torch.mul(tensor1,tensor2)

tensor([ 3, 30, 72])

In [484]:
# Subtraction
tensor1 - 1

tensor([0, 4, 7])

In [485]:
#addition
torch.add(tensor1,1) # add is short form for addition

tensor([2, 6, 9])

In [486]:
torch.add(tensor1,tensor2)

tensor([ 4, 11, 17])

In [487]:
# Division
torch.div(tensor1,2)

tensor([0.5000, 2.5000, 4.0000])

###Matrix multiplication
there are two ways to perform multiplication in neural neywroks and deep learning
1. Element-Wise multiplication
2. Matrix multiplication(Dot product)



In [488]:
#element-wise multiplication
tensor3=torch.tensor([1,3,5])
tensor4=torch.tensor([2,4,6])
print(tensor3,"*",tensor4)

tensor([1, 3, 5]) * tensor([2, 4, 6])


In [489]:
print(f"Equals: {tensor3*tensor4}")

Equals: tensor([ 2, 12, 30])


In [490]:
# Matrix  multiplication
torch.matmul(tensor3,tensor4)

tensor(44)

In [491]:
# Matrix maltiplication by hand
2*1+ 3*4+ 5*6
#using for loop

import time
start =time.time()
value=0
for i in range(len(tensor3)):
  value += tensor3[i]*tensor4[i]
  print(value)
end=time.time()
print(f"Total time taken: {end - start:.4f} seconds")


tensor(2)
tensor(14)
tensor(44)
Total time taken: 0.0020 seconds


In [492]:
%%time
torch.matmul(tensor3,tensor4)

CPU times: user 83 µs, sys: 4 µs, total: 87 µs
Wall time: 94.2 µs


tensor(44)

In [493]:
tensort1=torch.tensor([[1,2,3],[4,5,6]])
tensort2=torch.tensor([[1,3,5],[2,4,6],[1,3,5]])
torch.matmul(tensort1,tensort2)


tensor([[ 8, 20, 32],
        [20, 50, 80]])

built_in functions are prefered more as they are FAST

Note : there are two rules that performing matrix multiplication needs
to satisfy:

1. the inner dimensions must match
* the number of columns of first matrix must be equal to number of rows of 2nd matrix
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [494]:
# will not work and we get an error
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# will work as inner dimensions match
torch.matmul(torch.rand(2,3),torch.rand(3,2))

In [ ]:
torch.matmul(torch.rand(10,3),torch.rand(3,10))

 One of the most common error in deep learning is **Shape error**

In [ ]:
# shapes for matrix multiplication
tensor_a=torch.tensor([[1,2],[3,4],[4,5]])
tensor_b=torch.tensor([[5,6],[7,8],[9,10]])
torch.mm(tensor_a,tensor_b) # mm is same as torch.matmul

In [ ]:
tensor_a.shape,tensor_b.shape

1. To fix our tensor shape issues , we can manipulate the shape of one of our tensor  a **Transpose**
* A Transpose switches the axes or dimension of given tensor

In [ ]:
# Tensor before transpose
tensor_b

In [ ]:
# Tensor after Transpose
tensor_b_t=tensor_b.T
print(tensor_b_t)
tensor_b_t.shape

In [ ]:
# The matrix multiplication operation works when tensor_b is transposed
print(f'original shapes: tensor_a = {tensor_a.shape}, tensor_b = {tensor_b.shape}')
print(f'New shapes after transpose: tensor_a = {tensor_a.shape} (same as above), tensor_b.T = {tensor_b.T.shape}')
print(f'multipying: {tensor_a.shape} @ {tensor_b.T.shape} <- inner dimensions mus match')
print("output: \n")
output=torch.mm(tensor_a,tensor_b.T)
print(output)
print(f"\noutput shape :  {output.shape}")



### Finding the min, max,mean,sum,etc(Tensor aggrigation)

In [ ]:
#create a tensor
x=torch.arange(start=3,end=33, step=3 )
x

In [495]:
# Find min
torch.min(x)

tensor(3)

In [496]:
# find max
torch.max(x)

tensor(27)

In [497]:
#Find the mean
# mean works only on float or complex datatype.it do not wrok on long datatype
# The torch.mean() function requires a tensor of float 32 to work
torch.mean(x  , dtype=torch.float32 )

tensor(15.)

In [498]:
# Find sum
torch.sum(x)

tensor(135)

In [499]:
# we can use both ways
x.sum()

tensor(135)

### Finding the positional min and max using argmin and argmax

In [500]:
# create a tensor
x1=torch.arange(start=5,end=55,step=5)
x1

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [501]:
# First printing min
# then printing position of that min
print(f"minimun : {x1.min()}")
print(f"Position of min : {x1.argmin()}") # Find the position i tensor that has minimum value with argmin()-> returns index position of min tensor

minimun : 5
Position of min : 0


In [502]:
x1[0]

tensor(5)

In [503]:
# Find the of tensor where value is max
x1.argmax()

tensor(9)

In [504]:
x1[9]

tensor(50)

## Reshaping ,stacking,squeezing,and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape .Changes the shape of a tensor without changing its data.
*  View - return a view of an input tensor of certain shape but keep the same memory as orignal tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side(hstack)
* Squeeze - removes all `1` dimensions from tensor
* Unsqueez - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permutes (swapped ) in a certain way


#### Reshape

In [505]:
# create a tensor
r1= torch.arange(1.,15.)
r1,r1.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.]),
 torch.Size([14]))

In [506]:
# add extra dimensions
# reshape has to be compatable with orignal size of tensor .
# only those shapes are valid that after multiplying make the orignal size of tensor
# as in this case the orignal size is 14 we reshaped it as (2,7) that after multiplying 2 with 7 we get the orignal size that is 14
r1_reshaped=r1.reshape(2,7)
r1_reshaped,r1_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11., 12., 13., 14.]]),
 torch.Size([2, 7]))

In [507]:
r2_reshaped=r1.reshape(14,1)
r2_reshaped,r2_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.],
         [13.],
         [14.]]),
 torch.Size([14, 1]))

#### View

In [508]:
#change the  view
#new_tensor.reshape(2,7)
t6=torch.tensor([1,3,5,6,9,11])
new_tensor1=t6.view(1,6)
new_tensor1,new_tensor1.shape

(tensor([[ 1,  3,  5,  6,  9, 11]]), torch.Size([1, 6]))

In [509]:
#changing z changes x (because a view of tensor share the same memory as the orignal )
new_tensor1[:,0]=6
new_tensor1,t6

(tensor([[ 6,  3,  5,  6,  9, 11]]), tensor([ 6,  3,  5,  6,  9, 11]))

#### Stack

In [510]:
# Stack  tensor on each other
t6_stacked=torch.stack([t6,t6,t6] ,dim=1)
t6_stacked

tensor([[ 6,  6,  6],
        [ 3,  3,  3],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 9,  9,  9],
        [11, 11, 11]])

#### Squeeze

In [511]:
# torch.squeeze() remove all the singlr dimensions from the target tensor
# Tensor before squeezing
tensor10=torch.tensor([[1,2,3,4,7,6]])
print(f" Tensor before squeezing: {tensor10}")
print(f"shape of tensor before squeezing: {tensor10.shape}")


 Tensor before squeezing: tensor([[1, 2, 3, 4, 7, 6]])
shape of tensor before squeezing: torch.Size([1, 6])


In [512]:
tensor10_squeezed=tensor10.squeeze()
tensor10_squeezed, tensor10_squeezed.shape
print(f" Tensor after squeezing: {tensor10_squeezed}")
print(f"shape of tensor after squeezing: {tensor10_squeezed.shape}")


 Tensor after squeezing: tensor([1, 2, 3, 4, 7, 6])
shape of tensor after squeezing: torch.Size([6])


#### Unsqueezing

In [513]:
# torch.unsqueeze() add a single dimension to a target tensor at specific dim
print(f"previous squeezed tensor :{tensor10_squeezed}")
print(f"shape of squeezes tensor:{tensor10_squeezed.shape}")

# now we will unsqueeze it means add an extra dimension in it
tensor10_unsqueezed=tensor10_squeezed.unsqueeze(dim=0)
print(f" new unsqueezed tensor: { tensor10_unsqueezed }")
print(f" shape of unsqueezed tensor: {tensor10_unsqueezed.shape}")




previous squeezed tensor :tensor([1, 2, 3, 4, 7, 6])
shape of squeezes tensor:torch.Size([6])
 new unsqueezed tensor: tensor([[1, 2, 3, 4, 7, 6]])
 shape of unsqueezed tensor: torch.Size([1, 6])


#### Permute

In [514]:
# torch.permute -> rearranges the dimensionsof a target tensor in a specified order
# permute commonly used with images
org_tensor=torch.rand(3,244,244) #[ color channel, height,width]

#permute the orignal tensor to rearrange the axis (or dim) order
permuted_tensor=org_tensor.permute(2,1,0) #shift dim 0->1 ,1->2, 2->0
print(f"orignal tensor shape: {org_tensor.shape}")
print(f"permuted tensor shape: { permuted_tensor.shape}")# height,width,colorchannel

#both share the same memory orignal tensor shares the same memory as permuted tensor

orignal tensor shape: torch.Size([3, 244, 244])
permuted tensor shape: torch.Size([244, 244, 3])


In [515]:
org_tensor[0,0,0]

tensor(0.1611)

In [516]:
# if we change any value in orignal tensor it well also be changed  in permuted tensor as bot share the same memory
org_tensor[0,0,0]=0.8740



In [517]:
permuted_tensor[0,0,0]

tensor(0.8740)

#### Indexing (Selecting data from tensor)
indexig in pytorch is similar to  in numpy

In [518]:
#create a tensor
x=torch.arange(3,30,3)
print(f"tensor before reshaping: {x}")
print(f"shape of tensor before reshaping: {x.shape}")
x_re=x.reshape(1,3,3)
print(f"tensor after reshaping: {x_re}")
print(f"shape of tensor after reshaped: {x_re.shape}")



tensor before reshaping: tensor([ 3,  6,  9, 12, 15, 18, 21, 24, 27])
shape of tensor before reshaping: torch.Size([9])
tensor after reshaping: tensor([[[ 3,  6,  9],
         [12, 15, 18],
         [21, 24, 27]]])
shape of tensor after reshaped: torch.Size([1, 3, 3])


In [519]:
# index of reshaped tensor
x_re[0]

tensor([[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]])

In [520]:
#index on middle bracket(dim=1)
x_re[0,0] # x_re[0][0 both are same]


tensor([3, 6, 9])

In [521]:
x_re[0,1]

tensor([12, 15, 18])

In [522]:
x_re[0,2]

tensor([21, 24, 27])

In [523]:
x_re[0,0,1]

tensor(6)

In [524]:
# index on most inner bracket  last dim
x_re[0,0,0]

tensor(3)

In [525]:
x_re[0,1,0]

tensor(12)

In [526]:
x_re[0,2,2]

tensor(27)

In [527]:
# can use ":" to select  aff of the target dimension

In [528]:
x_re[:,0]

tensor([[3, 6, 9]])

In [529]:
x_re[:,1]

tensor([[12, 15, 18]])

In [530]:
# get all the values  of oth and 1st dimension but only index 1 of 2nd dim
x_re[:, : ,0]

tensor([[ 3, 12, 21]])

In [531]:
# get all the values of 0 dimension but only the 1 index value of 1st and 2nd dimension
# get 2nd element of second row
x_re[:,1,1]

tensor([15])

In [532]:
#get 0 index o of 0th and 1st dimension and all the values of 2nd dimension
x_re[0,0,:]

tensor([3, 6, 9])

In [533]:
#index to return 27
x_re[0,2,2]

tensor(27)

In [534]:
# index to return  9,18,27
x_re[:,:,2]

tensor([[ 9, 18, 27]])

## pytorch tensors and numpy
* NumPy is a Python library used for fast numerical computations and working with arrays.

1. change data from numpy array to pytorch tensor ->`torch.from_numpy(ndarray)`
2. change from pytorch to NumP -> `torch.tensor.numpy`

In [535]:
# numpy array to tensor
arr1=np.arange(1.,11.,1.)
print(f"numpy array: {arr1}")
ten1=torch.from_numpy(arr1) # while converting from numpy to pytorch reflects default datatype of array that is float 64
print(f"After conversion into tenor: {ten1} ")
print (f"Data type: {ten1.dtype}")
# default numpy data type is float64 and for tensors it is float32

numpy array: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
After conversion into tenor: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64) 
Data type: torch.float64


In [536]:
# change the valur of array . what it will do to tensor?
arr1=arr1+1 # the values in the tensor made from array  does not change even if we chnage values in orignal array
arr1,ten1

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [537]:
# Tensor to numpy array
ten2=torch.tensor([1.,2.,3.,4.])
print(f"Tensor before conversion into array: {ten2}")
tensor_to_numpy=ten2.numpy()
print(f"Tensor after conversion into array: {tensor_to_numpy}")
tenser_to_numpy.dtype # datatype will be the one you have assigned to tensor before conversion by default it is float32


Tensor before conversion into array: tensor([1., 2., 3., 4.])
Tensor after conversion into array: [1. 2. 3. 4.]


dtype('float32')

In [538]:
# if we change values in tensor will that affect the array values
ten2=ten2+1
ten2,tensor_to_numpy
#values in array will not chnage

(tensor([2., 3., 4., 5.]), array([1., 2., 3., 4.], dtype=float32))

## Reproducbility (trying to take random out of random)
* In short how neural network learns
` start with random numbers ->  Tensor opertion -> update random numbers to try and make them better representation of data -> again -> again ->agian .... `
* To reduce the randomness in neural network and pytorch comes the concept of a **Random Seed**
1. Random seed "flavour" the randomness

In [539]:
# create 2 random tensors
random_tensor1=torch.rand(4,3)
random_tensor2=torch.rand(4,3)
print(random_tensor1)
print(random_tensor2)
print(random_tensor1==random_tensor2)

tensor([[0.5766, 0.8764, 0.8779],
        [0.6731, 0.6362, 0.8230],
        [0.1302, 0.1416, 0.4901],
        [0.6446, 0.1680, 0.6516]])
tensor([[0.7159, 0.5130, 0.6978],
        [0.8230, 0.0809, 0.9740],
        [0.6509, 0.5285, 0.5211],
        [0.4960, 0.8270, 0.1687]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])


In [540]:
# lets make some random but reproducible tensors
#set the random seed
RANDOM_SEED=42 # 42 is universal and most common value for random_seed .the value of random_seed can be any value you like

torch.manual_seed(RANDOM_SEED)
#now create random tensors with the flavour of random seed
random_tensor3=torch.rand(4,3)

torch.manual_seed(RANDOM_SEED) #in nooteboke it only work for one block of code
random_tensor4=torch.rand(4,3)

print(random_tensor3)
print(random_tensor4)
print(random_tensor3==random_tensor4)



tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])


## Runing tensors and pytorch objects on the GPUs(making the computation faster
* GPU = faster computation  on numbers , thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes to make everything good


####  1. Getting a GPU
* easiest - use google colab for free gpu
* Use your own GPU - take a little bit of setup , set it on your own system
* use cloud computing(rent from cloud) -AWS,Azure - allowa you to rent computers on the cloud and access them

In [3]:
!nvidia-smi

Wed Jul 30 14:01:06 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
# AS we are trying to use the GPU from gogle colab free version
# First we need to check that even a GPU is available at this time or not
#check GPU access with pytorch
import torch
torch.cuda.is_available()




True

In [6]:
#setup device agnostic code
# If GPU is available change the device from CPU to GPU
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [9]:
#count number of devices
torch.cuda.device_count()

1

## putting tensors ( and models ) on GPU
* The reason we want our tensors /models on GPU is because using GPU results in faster computations

In [10]:
# create tensor (default on the CPU)
tensor =torch.tensor([1,2,3,4])
# tensor is not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3, 4]) cpu


In [11]:
# Move tensor to GPU if available
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3, 4], device='cuda:0')

#### Moving tensors back to the CPU
numpy array works on CPU

In [12]:
# if tensor is on GPU it cannot  be transformed into numpy
tensor_on_gpu.numpy()
# 3rd main issue that we face in deep learning as we have talked about it above


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [13]:
# to fix  the GPU tensor withnumpy issue , we can first set it to the CPU
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3, 4])